### PR TITLE
WIP R3 driver

### PR DESCRIPTION
**Pull request by wolfv**
This is still WIP but it already allows the user to e.g. use service calls to upload a MELFA BASIC program to the robot, execute the program, read the robot state, toggle the robot servo / control state etc.

For real applications this will be quite useful I think, as one can control the robot remotely + without the teaching control, and without having to run a copy of RT Toolbox 3 which doesn't work under linux.

Let me know what you think! I am also happy to adjust the coding style to your preferences.

Wolf

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
> For real applications this will be quite useful I think, as one can control the robot remotely + **without the teaching control** [..]

Does the controller also need to be put into `REMOTE` control mode (or whatever the equivalent is for Mitsubishi), or does this work without such a setting?

**Comment by wolfv** [comment]
Hi @gavanderhoorn 
the robot will have to have be set to automatic mode. For this, one needs to either have a separate device with the switch connected to the CNUSR11 interface on the front of the robot controller, or as we did it, connect the required pins by wires (also need to connect the emergency switch and the door safety switch if one doesn't have those). (of course this is not the safest practice).

Additionally if a Teaching Control is connected, it needs to be *disabled* in automatic mode (small light switch at the back).

In the manual mode, one can send those commands from the teaching control.

That's at least how it works on the Mitsubishi! I hope I'll find some time to write this up because it took me a while to get used to all of this.

**Comment by gavanderhoorn** [comment]
> I hope I'll find some time to write this up because it took me a while to get used to all of this.

I would certainly recommend to do this, because although it would seem to be a standard setup for configuring robots for remote control, it's not always obvious to (casual) users.

Just wanted to make sure the driver is not circumventing any safety procedures.

**Comment by 7675t** [comment]
@wolfv Do you have particular reason to close this PR? If not, could you please remain open this for the future development? I personally don't have MELFA robot and time to check it for a while but someone may be interested in using this feature.

**Pull request closed without merging**
